version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.13.10
    - 7.13.17
    - 7.13.4
    - 7.13.7
    - 7.13.9
  - dependency-name: "@octokit/rest"
    versions:
    - 18.1.0
    - 18.1.1
    - 18.2.0
    - 18.2.1
    - 18.3.1
    - 18.3.2
    - 18.3.3
    - 18.3.4
    - 18.3.5
    - 18.4.0
    - 18.5.0
    - 18.5.3
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.13.1
    - 7.13.10
    - 7.13.14
    - 7.13.15
    - 7.13.16
  - dependency-name: markdown-it
    versions:
    - 12.0.5
    - 12.0.6
  - dependency-name: rollup
    versions:
    - 2.38.3
    - 2.38.4
    - 2.38.5
    - 2.39.1
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.3
    - 2.41.4
    - 2.41.5
    - 2.42.0
    - 2.42.2
    - 2.42.3
    - 2.42.4
    - 2.43.1
    - 2.44.0
    - 2.45.0
    - 2.45.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.15
    - 7.13.5
    - 7.13.9
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.12.13
    - 7.12.15
    - 7.13.10
    - 7.13.15
    - 7.13.4
    - 7.13.7
    - 7.13.9
  - dependency-name: katex
    versions:
    - 0.13.0
    - 0.13.1
    - 0.13.2
  - dependency-name: polka
    versions:
    - 1.0.0-next.13
    - 1.0.0-next.14
  - dependency-name: highlight.js
    versions:
    - 10.6.0
    - 10.7.1
    - 10.7.2
  - dependency-name: svelte
    versions:
    - 3.32.1
    - 3.32.2
    - 3.32.3
    - 3.34.0
    - 3.35.0
    - 3.36.0
    - 3.37.0
  - dependency-name: "@rollup/plugin-commonjs"
    versions:
    - 18.0.0
  - dependency-name: markdown-it-anchor
    versions:
    - 7.0.2
    - 7.1.0
  - dependency-name: marked
    versions:
    - 2.0.1
  - dependency-name: "@rollup/plugin-replace"
    versions:
    - 2.4.0
    - 2.4.1
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.2.0
  - dependency-name: "@rollup/plugin-babel"
    versions:
    - 5.3.0
  - dependency-name: sirv
    versions:
    - 1.0.11
